Section "ServerFlags"
	Option "AutoAddDevices" "false"
	Option "AutoEnableDevices" "false"
	Option "AllowEmptyInput" "false"
	Option "UseSysfsDevices" "false"
EndSection

# Internal keyboard
Section "InputDevice"
    Identifier "Keyboard0"
    Driver "evdev"
    Option "Device" "/dev/input/kbd"
EndSection

# Internal touchpad
Section "InputDevice"
    Identifier "Touchpad0"
    Driver "synaptics"
    Option "Device" "/dev/input/mouse"
EndSection

Section "InputDevice"
    Identifier "TrackPoint"
    Driver "evdev"
    Option "Device" "/dev/input/trackpoint"
EndSection

# # Internal extra keys (like brightness)
# Section "InputDevice"
#     Identifier "ThinkPadExtraKeys"
#     Driver "evdev"
#     Option "Device" "/dev/input/extrabuttons"
# EndSection

# Layout
Section "ServerLayout"
    Identifier "DefaultLayout"
    InputDevice "Keyboard0" "CoreKeyboard"
    InputDevice "Touchpad0" "CorePointer"
	# InputDevice "ThinkPadExtraKeys" "SendCoreEvents"
	InputDevice "TrackPoint" "SendCoreEvents"
EndSection

