# bluetooth
blacklist btusb 

# ethernet
blacklist r8169

# webcam
blacklist uvcvideo

# motherboard speaker
blacklist pcspkr

# old joystick interface
blacklist joydev

# EFI persistent crash logs
blacklist efi_pstore

# raw serio/PS2 access
blacklist serio_raw

# intel watchdog ???
blacklist iTCO_wdt

# VM
blacklist kvm_intel

# TPM
blacklist tpm_tis

# input leds
blacklist input_leds
